/*
 * Created on 2017-02-23 ( Date ISO 2017-02-23 - Time 15:38:19 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package td.td3.service2.commons;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 * JPA environment for JPA operations execution <br>
 * Provided by Telosys Tools for JPA testing
 * 
 */
public class JpaEnvironmentV1 {

	private final static String persistenceUnitName = "td" ; 
	
	private final static EntityManagerFactory emf = Persistence.createEntityManagerFactory(persistenceUnitName); 
	
	public final static void fake() {
	}
	
	public final static String getPersistenceUnitName() {
		return persistenceUnitName ;
	}
	
	public final static EntityManagerFactory getEntityManagerFactory() {
		return emf ;
	}
	
	public final static EntityManager createEntityManager() {
		return emf.createEntityManager() ;
	}
}
