/*
 * Created on 2017-02-23 ( Date ISO 2017-02-23 - Time 15:38:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package td.td3.service2.commons;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;

/**
 * JPA operation interface
 * Provided by Telosys Tools for JPA testing
 *
 */
public interface JpaOperation {

	/**
	 * Executes a JPA operation using the given EntityManager
	 * @param em the EntityManager to be used
	 * @return
	 * @throws PersistenceException
	 */
	public Object execute(EntityManager em) throws PersistenceException;
	
}
