/*
 * Created on 2017-02-23 ( Date ISO 2017-02-23 - Time 15:38:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package td.td3.service2;


import javax.persistence.EntityManager;

import td.entities.Author;
import td.td3.service2.commons.JpaEnvironmentV1;

//import javax.inject.Named;

/**
 * Car persistence service - JPA implementation 
 * 
 * @author Telosys 
 *
 */
//@Named("CarPersistence")
//public class CarPersistenceJpa extends GenericJpaService<CarJpaRecord, Integer> implements CarPersistence {
public class AuthorDAO {

//	/**
//	 * Constructor
//	 */
//	public CarPersistenceJpa() {
//		super(CarJpaRecord.class);
//	}
//

	public Author findById( Integer id ) {
		Author entity = null ;
		EntityManager em = JpaEnvironmentV1.createEntityManager() ;
		try {
			entity = em.find(Author.class, id);
		} catch (Exception e) {
			throw new RuntimeException("findById error", e);
		}
		finally {
			em.close();
		}
		return entity ;
	}

	public void create(Author entity) {
		EntityManager em = JpaEnvironmentV1.createEntityManager() ;
		try {
			em.getTransaction().begin();
			em.persist(entity);
			em.getTransaction().commit();
		} catch (Exception e) {
			throw new RuntimeException("create error", e);
		}
		finally {
			em.close();
		}
	}
	
	public boolean update(Author entity) {
		boolean ret = false ;
		EntityManager em = JpaEnvironmentV1.createEntityManager() ;
		try {
			if ( em.find(Author.class, entity.getId() ) != null ) {
				em.getTransaction().begin();
				em.merge(entity);
				em.getTransaction().commit();
				ret = true ;
			}
		} catch (Exception e) {
			throw new RuntimeException("update error", e);
		}
		finally {
			em.close();
		}
		return ret ;
	}

	public void save(Author entity) {
		EntityManager em = JpaEnvironmentV1.createEntityManager() ;
		try {
			em.getTransaction().begin();
			em.merge(entity);
			em.getTransaction().commit();
		} catch (Exception e) {
			throw new RuntimeException("save error", e);
		}
		finally {
			em.close();
		}
	}

	public void deleteById( Integer id ) {
		EntityManager em = JpaEnvironmentV1.createEntityManager() ;
		try {
			final Author entity = em.find(Author.class, id);
			if ( entity != null ) {
				em.getTransaction().begin();
				em.remove(entity);
				em.getTransaction().commit();				
			}
		} catch (Exception e) {
			throw new RuntimeException("deleteById error", e);
		}
		finally {
			em.close();
		}
	}

	public void delete(Author entity) {
		if ( entity != null ) {
			deleteById( entity.getId() );
		}
	}

//	@Override
//	public long countAll() {
//		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countAll") ) ;
//		return count.longValue();
//	}
//
//	public long countById(Integer id) {
//		Long count = (Long) super.execNamedQueryWithSingleResult( buildQueryName("countById"), id ) ;
//		return count.longValue();
//	}
//	
//	@Override
//	public boolean exists(Integer id) {
//		long count = countById(id) ;
//		return count > 0 ;
//	}
//
//
//	@Override
//	public boolean exists(Author record) {
//		if ( record != null ) {
//			return exists( record.getId() );
//		}
//		return false ;
//	}
//
//	@SuppressWarnings("unchecked")
//	public List<Author> queryExample() {
//		List<?> list = super.execNamedQuery(buildQueryName("theNamedQueryToBeUsed")) ;
//		return (List<CarJpaRecord>) list ;
//	}
//
}
